// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "rekognition-demo.ecloudvalley.com",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3pmshzfi87uy0.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:0f57fc50-7fb3-489e-b696-73b782c7be6e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_P2IhL44W5",
    "aws_user_pools_web_client_id": "6vokq44gv9adnubetcq8mphu22",
    "aws_cloud_logic_custom": [
        {
            "name": "api6832f3b1",
            "endpoint": "https://jzpx14qz5e.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "image-pool-ecv",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
